### ISSUE TITLE
ImportError: cannot import name make_dsn

### ISSUE THREAD

**Issue by shepilov-vladislav** [Vauxoo/odoo-profiler#30]
branch 8.0

```
2017-06-23 08:44:11,197 1295 CRITICAL openerp_template openerp.service.server: Failed to initialize database `openerp_template`.
Traceback (most recent call last):
File "/root/odoo-8.0/openerp/service/server.py", line 937, in preload_registries
registry = RegistryManager.new(dbname, update_module=update_module)
File "/root/odoo-8.0/openerp/modules/registry.py", line 370, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/root/odoo-8.0/openerp/modules/loading.py", line 312, in load_modules
modobj.update_list(cr, SUPERUSER_ID)
File "/root/odoo-8.0/openerp/api.py", line 268, in wrapper
return old_api(self, *args, **kwargs)
File "/root/odoo-8.0/openerp/addons/base/module/module.py", line 651, in update_list
handler.load_addons()
File "/root/odoo-8.0/openerp/http.py", line 1317, in load_addons
m = __import__('openerp.addons.' + module)
File "/root/odoo-8.0/openerp/modules/module.py", line 80, in load_module
mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
File "/root/odoo-profiler/profiler/__init__.py", line 5, in <module>
from . import controllers
File "/root/odoo-profiler/profiler/controllers/__init__.py", line 5, in <module>
from . import main
File "/root/odoo-profiler/profiler/controllers/main.py", line 20, in <module>
from openerp.addons.profiler.hooks import CoreProfile as core
File "/root/odoo-profiler/profiler/hooks.py", line 9, in <module>
from psycopg2.extensions import make_dsn
ImportError: cannot import name make_dsn
```

**Comment by moylop260** [comment]
thanks for report

What version of psycopg are you using?
pip list | grep psycopg

Could you try updating it?

**Comment by moylop260** [comment]
the logs looks like as a container generated with t2d
Are you using travis or runbot or something similar to share your build link

**Comment by shepilov-vladislav** [comment]
```
psycopg2 (2.6.2)
```

**Comment by moylop260** [comment]
I'm using `psycopg2 (2.7.1)`
Could you try upgrade it:
`pip install --upgrade psycopg2==2.7.1`

Or apply the following patch https://github.com/Vauxoo/odoo-profiler/pull/31

**Comment by shepilov-vladislav** [comment]
Great TY!
